version: '3.9'

services:
  eureka-server:
    build: ./eureka-server
    container_name: micromart-eureka-server
    ports:
      - "8761:8761"
    networks:
      - micromart

  api-gateway:
    build: ./api-gateway
    container_name: micromart-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - micromart

  auth-service:
    build: ./auth-service
    container_name: micromart-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - redis
      - authdb
    networks:
      - micromart

  authdb:
    image: mysql:8.0
    container_name: micromart-authdb
    environment:
      MYSQL_ROOT_PASSWORD: Manoj@8719895574
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    networks:
      - micromart

  product-service:
    build: ./product-service
    container_name: micromart-product-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - productdb
    networks:
      - micromart

  productdb:
    image: mysql:8.0
    container_name: micromart-productdb
    environment:
      MYSQL_ROOT_PASSWORD: Manoj@8719895574
      MYSQL_DATABASE: productdb
    ports:
      - "3307:3306"
    networks:
      - micromart

  order-service:
    build: ./order-service
    container_name: micromart-order-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - kafka
      - orderdb
    networks:
      - micromart

  orderdb:
    image: mysql:8.0
    container_name: micromart-orderdb
    environment:
      MYSQL_ROOT_PASSWORD: Manoj@8719895574
      MYSQL_DATABASE: orderdb
    ports:
      - "3308:3306"
    networks:
      - micromart

  inventory-service:
    build: ./inventory-service
    container_name: micromart-inventory-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - inventorydb
    networks:
      - micromart

  inventorydb:
    image: mysql:8.0
    container_name: micromart-inventorydb
    environment:
      MYSQL_ROOT_PASSWORD: Manoj@8719895574
      MYSQL_DATABASE: inventorydb
    ports:
      - "3309:3306"
    networks:
      - micromart

  payment-service:
    build: ./payment-service
    container_name: micromart-payment-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - kafka
      - paymentdb
    networks:
      - micromart

  paymentdb:
    image: mysql:8.0
    container_name: micromart-paymentdb
    environment:
      MYSQL_ROOT_PASSWORD: Manoj@8719895574
      MYSQL_DATABASE: paymentdb
    ports:
      - "3310:3306"
    networks:
      - micromart

  notification-service:
    build: ./notification-service
    container_name: micromart-notification-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - notificationdb
    networks:
      - micromart

  notificationdb:
    image: mysql:8.0
    container_name: micromart-notificationdb
    environment:
      MYSQL_ROOT_PASSWORD: Manoj@8719895574
      MYSQL_DATABASE: notificationdb
    ports:
      - "3311:3306"
    networks:
      - micromart

  redis:
    image: redis:7.0
    container_name: micromart-redis
    ports:
      - "6379:6379"
    networks:
      - micromart

  zookeeper:
    image: bitnamilegacy/zookeeper:3.8
    container_name: micromart-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - micromart

  kafka:
    image: bitnamilegacy/kafka:3.2
    container_name: micromart-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - micromart

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: micromart-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - micromart

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: micromart-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - micromart

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: micromart-logstash
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - micromart

networks:
  micromart:
    driver: bridge
